name: Deploy Next.js to Linux Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Buildar o projeto Next.js
        run: npm run build

      - name: Criar diretório remoto
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: mkdir -p /dados/webapps/ecommerce-ui

      - name: Enviar build via SCP (SSH)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: |
            .next/**
            
          target: /dados/webapps/ecommerce-ui/
          overwrite: true
          rm: true
          debug: true

      - name: Reiniciar aplicação via PM2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /dados/webapps/ecommerce-ui
            npm ci --omit=dev
            pm2 restart ecommerce-ui || pm2 start npm --name "ecommerce-ui" -- start
