name: Deploy Next.js to Linux Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout do código
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2️⃣ Configurar Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # 3️⃣ Instalar dependências
      - name: Instalar dependências
        run: npm ci

      # 4️⃣ Buildar o projeto Next.js
      - name: Buildar o projeto Next.js
        run: npm run build

      # 5️⃣ Criar diretório no servidor (se ainda não existir)
      - name: Criar diretório remoto
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: mkdir -p /dados/webapps/ecommerce-ui

      # 6️⃣ Enviar artefatos via SCP
      - name: Enviar build via SCP (SSH)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: |
            .next/**
            package.json
            package-lock.json
            public/**
            next.config.js
          target: /dados/webapps/ecommerce-ui/
          overwrite: true
          rm: true
          debug: true

      # 7️⃣ Reiniciar aplicação via PM2
      - name: Executar comandos remotos (restart PM2)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /dados/webapps/ecommerce-ui
            npm ci --omit=dev
            pm2 restart ecommerce-ui || pm2 start npm --name "ecommerce-ui" -- start
